In [12]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
import pickle
import matplotlib.pyplot as plt

In [15]:
path = 'Data Folder Path'
images = []
classNames = []
for entry in os.scandir(path):
        # Check if the entry is a directory
        if entry.is_dir():
            # Process the folder (subdirectory)
            folder_path = entry.path
            folder_name = os.path.basename(folder_path)
            for filename in os.listdir(folder_path):
                # Check if the file is a video file (you can add more video file extensions if needed)
                if filename.endswith(".jpg"):
                    curImg = cv2.imread(os.path.join(folder_path, filename))
                    images.append(curImg)
                    classNames.append(folder_name)


In [31]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
        print(img)
    return encodeList

[[[208 207 203]
  [208 207 203]
  [208 207 203]
  ...
  [219 218 216]
  [219 218 216]
  [219 218 216]]

 [[208 207 203]
  [208 207 203]
  [208 207 203]
  ...
  [219 218 216]
  [219 218 216]
  [219 218 216]]

 [[208 207 203]
  [208 207 203]
  [208 207 203]
  ...
  [219 218 216]
  [219 218 216]
  [219 218 216]]

 ...

 [[199 198 194]
  [204 203 199]
  [214 214 214]
  ...
  [192 191 187]
  [192 191 187]
  [193 192 188]]

 [[197 196 192]
  [213 212 208]
  [205 205 205]
  ...
  [192 191 187]
  [192 191 187]
  [193 192 188]]

 [[197 196 192]
  [213 212 208]
  [205 205 205]
  ...
  [192 191 187]
  [192 191 187]
  [193 192 188]]]
[[[208 205 200]
  [208 205 200]
  [208 205 200]
  ...
  [219 218 214]
  [219 218 214]
  [219 218 214]]

 [[207 204 199]
  [207 204 199]
  [207 204 199]
  ...
  [219 218 214]
  [219 218 214]
  [219 218 214]]

 [[207 204 199]
  [207 204 199]
  [207 204 199]
  ...
  [219 218 214]
  [219 218 214]
  [219 218 214]]

 ...

 [[196 192 189]
  [196 192 189]
  [196 192 189]
  ..

In [18]:
with open('path/to/filename.pkl', 'wb') as file:
    pickle.dump(classNames, file)

In [5]:
def markAttendance(name):
    with open('Attendance.csv', 'r+') as f:
        myDataList = f.readlines()


        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
            if name not in nameList:
                now = datetime.now()
                dtString = now.strftime('%H:%M:%S')
                f.writelines(f'\n{name},{dtString}')

In [1]:
##### for video only don't import it 

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
# img = captureScreen()
    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
# print(faceDis)
        matchIndex = np.argmin(faceDis)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
# print(name)
            y1, x2, y2, x1 = faceLoc
            y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)
            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
            markAttendance(name)

    cv2.imshow('Webcam', img)
    cv2.waitKey(1)

NameError: name 'cv2' is not defined

In [11]:
with open('F:/semester 7/vision/data/face_encodings.pkl', 'rb') as file:
    loaded_data = pickle.load(file)
encodeListKnown = loaded_data

img = face_recognition.load_image_file('F:/semester 7/vision/test.jpg')

#imgs = cv2.resize(img, (0, 0), None, 0.25, 0.25)
#imgs = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
facesCurFrame = face_recognition.face_locations(img)
encodesCurFrame = face_recognition.face_encodings(img)
result = []
for i in range(len(encodesCurFrame)):
    faceDis = face_recognition.face_distance(encodeListKnown, encodesCurFrame[i])

    matchIndex = np.argmin(faceDis)
    if faceDis[matchIndex] < 0.7:
        name = classNames[matchIndex]
        result.append(name)
        #top, right, bottom, left = facesCurFrame[i]
        #cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0), 2)

        y1, x2, y2, x1 = facesCurFrame[i]
        #y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)
        cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
        # #markAttendance(name)

#Display the image with faces
cv2.namedWindow('Detected Faces', cv2.WINDOW_NORMAL)
cv2.imshow('Detected Faces', cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
# #cv2.imshow('before Faces', cv2.cvtColor(imgSS, cv2.COLOR_RGB2BGR))

r =  set(result)
#print(classNames)
#print(result)
print(r)
print(len(r))

cv2.resizeWindow('Detected Faces', 300, 200)  # Adjust the size as needed
cv2.waitKey(0)
cv2.destroyAllWindows()

{'Ahmed Hagag_120200101', 'Mariam Ayman_120200094', 'Ahmed Mohamed_120200027', 'Asem Mohamed_120200089', 'Ahmed Abdelkader_120200028', 'Nour Alhuda_120200144', 'Youssef Zaghloul_120190057', 'Mostafa Ahmed_120200043', 'Youssef Ashraf_120200090', 'Alaa Moheb_120200212', 'Sohaila Mohamed_120200062', 'Bassant Tarek_120200244', 'Rowida Elsayed_120200181', 'Omnia Nabil_120200156', 'Noha Omar_120200211', 'Ahmed Fathi_120200245', 'Mohamed Ayman_120200081', 'Arwa Zakaria_120200059', 'Abdulrahman Essam_120200039', 'Ahmed Mongy_120200033', 'Ziad Hesham_120200078'}
21
